Repository hyukjin0419/TeamCheckMate, pull requests merged in 2024-02, with the labels that each got.

#194 css/#192: 카테고리 추가 페이지 만들기
  App.js
  screens/components/Category/CategoryAdd.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: css

#196 Refractor/#182: TeamItem 모달창에 이름 추가 #182
  screens/components/Team/TeamItem.js
Labels: refractor

#197 css/#195: PersonalPage 일주일 시간표에서 체크표 추가
  package-lock.json
  package.json
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
  screens/components/PersonalPageFolder/src/Style.js
Labels: css

#199 Css/#185: Add 버튼 위치 수정
  App.js
  screens/components/AssignmentPage.js
  screens/components/GuidancePage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
  screens/images/ClassAddBtn.png
  screens/images/CloseClassAddBtn.png
Labels: css

#201 Feat/#184: 팀 체크리스트 화면 구현
  App.js
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/Category/CategoryAdd.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
  screens/components/PersonalPageFolder/src/Locale.js
  screens/components/PersonalPageFolder/src/Style.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
  screens/components/TeamCheckPage.js
  screens/images/categoryAddBtn.png
  screens/images/categoryCloseBtn.png
  screens/images/icons/EditIcon.png
  screens/images/option.png
Labels: feat

#202 css,fix/#198: PersonalPage에서 css 수정
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
  screens/components/PersonalPageFolder/src/Style.js
Labels: fix, css

#207 fix/#206: TeamCheckPage navigation 이슈 수정
  screens/components/TeamCheckPage.js
Labels: fix

#209 Css/#200: TeamItem Modal Style 변경
  screens/components/Team/TeamItem.js
  screens/styles/css.js
Labels: css

#212 Css/#174: 참여코드 복사 버튼 스타일 수정
  screens/components/Team/TeamItem.js
  screens/styles/css.js
Labels: css

#215 Fix/#213: Color Palette 기능 수정
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamUpdatePage.js
Labels: fix

#219 Css,fix/#208: 과제 체크리스트 화면 구현
  screens/components/TeamCheckPage.js
Labels: fix, css

#220 Feat/#218: 과제 화면 팀메이트 레이블 추가
  screens/components/AssignmentPage.js
  screens/components/Team/TeamPage.js
  screens/images/icons/AssignmentAdd.png
  screens/images/icons/TeamMateAdd.png
  screens/styles/css.js
Labels: feat

#225 Css/#221: 하단 탭 바 수정
  App.js
  screens/images/PersonalIconSelected.png
  screens/images/PersonalIconUnselected.png
  screens/images/TeamIconSelected.png
  screens/images/TeamIconUnselected.png
Labels: css

#227 Css/#226: AssignmentItem Style 수정
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
Labels: css

#231 Bug/#228: 과제 수정, 삭제 버그 해결
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
Labels: bug

#233 Css/#232: 과제 아이템 모달 스타일 수정
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/Team/TeamItem.js
Labels: css

#236 Css/#234: 팀원레이블 스타일 변경
  screens/components/AssignmentPage.js
  screens/components/Team/TeamItem.js
Labels: css

#237 Feat/#229: 팀원 정보 표시 모달 구현
  screens/components/Team/TeamItem.js
  screens/images/modalXBtn.png
Labels: feat

#239 Feat/#238: 길라잡이 페이지 구현
  screens/components/GuidancePage.js
  screens/images/GuidancePageNoPost.png
  screens/styles/css.js
Labels: feat

#241 Feat/#235: TextInput 글자 수 제한
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/logins/UserInfoInputPage.js
  screens/styles/css.js
Labels: feat

#243 Feat/#242: 팀원 정보 모달창 닫기버튼 기능 구현
  screens/components/Team/TeamItem.js
Labels: feat

#246 Css/#244: 팀원 레이블 스타일 변경
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/SchedulePage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamJoinPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/styles/css.js
Labels: css

#249 Css/#247: 뒤로가기 아이콘 수정
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamJoinPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/components/TeamCheckPage.js
  screens/images/backBtn.png
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
  screens/styles/css.js
Labels: css

#250 Feat/#184: 팀 체크리스트 화면 구현
  package-lock.json
  package.json
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamUpdateAddMemberPage.js
  screens/components/TeamCheckPage.js
  screens/images/ListAddBtn.png
  screens/images/icons/three_dots.png
Labels: feat

#256 css,feat/#230: PersonalPage Add/Close버튼 + 백엔드 구현
  screens/components/Category/CategoryAdd.js
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/TeamCheckPage.js
  screens/images/icons/three_dots.png
Labels: feat, css

#258 Feat/#252: 팀 체크리스트 백엔드 구현 (미완)
  screens/components/TeamCheckPage.js
  screens/images/AssignmentContainer.png
  screens/images/GuidancePageNoPost.png
  screens/images/backBtn.png
  screens/images/icons/AssignmentAdd.png
  screens/images/icons/TeamMateAdd.png
  screens/images/modalXBtn.png
Labels: feat

#259 Feat/#252: 팀 체크리스트 백엔드 구현 (미완)
  screens/components/TeamCheckPage.js
  screens/images/AssignmentContainer.png
  screens/images/GuidancePageNoPost.png
  screens/images/backBtn.png
  screens/images/icons/AssignmentAdd.png
  screens/images/icons/TeamMateAdd.png
  screens/images/modalXBtn.png
Labels: feat

#262 Css/#261: 과제추가 모달창 스타일 맞추기
  screens/components/AssignmentPage.js
  screens/components/CategoryItem.js
Labels: css

#264 Css/#263: +버튼 모달 수정
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/Team/TeamPage.js
Labels: css

#265 Css/#255: 팀 체크리스트 과제 컨테이너 이미지 변경
  screens/components/CategoryItem.js
  screens/components/TeamCheckPage.js
  screens/images/icons/three_dots.png
Labels: css

#269 Bug/#266: TeamCheckPage indexOf 버그 해결하기
  screens/components/TeamCheckPage.js
Labels: bug

#270 Fix/#297: 과제화면 차례대로 불러오기
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/TeamCheckPage.js
Labels: fix

#271 Fix/#268: 체크리스트 체크 안된게 위로 렌더링 된게 하기
  screens/components/TeamCheckPage.js
Labels: fix

#273 Feat/#251: 하단 탭 바 스타일 수정
  App.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: feat

#274 But/#272: TeamCheckPage Flatlist id 문제 해결
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/Category/CategoryAdd.js
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
  screens/components/TeamCheckPage.js
Labels: bug

#275 Bug/#272: TeamCheckPage Flatlist id 문제 해결
  screens/components/AssignmentPage.js
  screens/components/TeamCheckPage.js
Labels: bug

#282 Fix/#280: AssignmentPage에 팀원 정보 모달창 버그 수정
  screens/components/AssignmentPage.js
  screens/components/Team/TeamItem.js
Labels: fix

#285 Feat/#240: 설정 화면 구현
  App.js
  screens/components/AppInformationPage.js
  screens/components/CategoryItem.js
  screens/components/SettingPage.js
  screens/components/TeamCheckPage.js
  screens/images/optionRight.png
Labels: feat

#289 Feat/#286: 햅틱 추가, 수정
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/CategoryItem.js
  screens/components/SettingPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamJoinPage.js
  screens/components/Team/TeamPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/components/TeamCheckPage.js
Labels: feat

#292 Css/#290: TeamCheckPage 과제 아이템 스타일 수정
  screens/components/AssignmentPage.js
  screens/components/TeamCheckPage.js
Labels: css

#295 Css/#293: 색상 팔레트 화살표 위치 조정
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamUpdatePage.js
Labels: css

#296 Feat/#294: 팀 아이템, 과제 아이템 long press 시 모달 띄우기
  screens/components/AssignmentItem.js
  screens/components/Team/TeamItem.js
Labels: feat

#297 Feat/#283: 팀체크리스트 delete 및 modify 구현
  screens/components/.TeamCheckPage.js.swp
  screens/components/AssignmentPage.js
  screens/components/TeamCheckPage.js
Labels: feat

#300 Fix/#291: TeamCheckPage update시 autoFocus문제 해결
  screens/components/TeamCheckPage.js
Labels: fix

#304 Fix/#291: TeamCheckPage update시 autoFocus문제 해결 #300
  screens/components/TeamCheckPage.js
Labels: fix

#305 Feat/#303: 팀체크리스트에서 체크리스트 작성시 중간에 textinput렌더링 하기
  screens/components/TeamCheckPage.js
Labels: feat

#307 Fix/#306: TeamCheckPage 수정시 공백일 때 기존 값으로 초기화 시키기 #306
  screens/components/TeamCheckPage.js
Labels: fix

#308 Feat/#299: 삭제 할 때 모달 띄우기
  screens/components/AssignmentItem.js
  screens/components/SettingPage.js
  screens/components/Team/TeamItem.js
  screens/styles/css.js
Labels: feat

#309 Fix/#306: TeamCheckPage 수정시 공백일 때 기존 값으로 초기화 시키기
  screens/components/TeamCheckPage.js
Labels: fix

#313 Css/#312: 모달 opacity 수정
  screens/components/AssignmentItem.js
  screens/components/Team/TeamItem.js
Labels: css

#319 fix/#317: PersonalPage 렌더링 수정
  screens/components/Category/CategoryAdd.js
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: fix

#321 fix/#320: Task 추가 렌더링 수정
  screens/components/CategoryItem.js
Labels: fix

#324 Feat/#315: SettingPage 하위 페이지들 만들기
  App.js
  screens/components/AppInformationPage.js
  screens/components/OpenSourcePage.js
  screens/components/PasswordResetPage.js
  screens/components/PrivatePolicyPage.js
  screens/components/SettingPage.js
  screens/components/TermsOfServicePage.js
  screens/components/UserInfoUpdatePage.js
Labels: feat

#329 feat/#322: Task CRUD 완성 하기
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: feat

#330 feat/#322
  screens/components/CategoryItem.js
Labels: feat

#333 Feat/#332: User Collection Checklist에 teamCode 및 teamTitle 추가하기
  screens/components/OpenSourcePage.js
  screens/components/PasswordResetPage.js
  screens/components/PrivatePolicyPage.js
  screens/components/TeamCheckPage.js
  screens/components/TermsOfServicePage.js
  screens/components/UserInfoUpdatePage.js
Labels: feat

#335 feat/#331: 팀 task 정보 PersonalPage 불러오게 하기
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/TeamCheckPage.js
Labels: feat

#337 feat/#336: PersonalPage에 팀 task CRUD 할 수 있게 하기
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/TeamCheckPage.js
Labels: feat

#339 comments/#338: WeeklyCalender 정리 하기
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: comments

#341 Fixed task CRUD issues
  screens/components/Category/CategoryAdd.js
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
Labels: fix

#342 Fix/#328: 팀체크리스트 TextInput
  screens/components/AppInformationPage.js
  screens/components/PrivatePolicyPage.js
  screens/components/SettingPage.js
  screens/components/TeamCheckPage.js
Labels: fix

#344 Css/#343: 팀체크페이지 스타일 수정
  screens/components/TeamCheckPage.js
Labels: css

#345 feat,fix/#288: 카테고리 날짜로 기준 + 체크 표시 날짜 버그 수정
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: feat, fix

#346 feat,fix/#288: 카테고리 날짜로 기준 + 체크 표시 날짜 버그 수정
  screens/components/CategoryItem.js
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
Labels: feat, fix
