Repository hyukjin0419/TeamCheckMate, pull requests merged in 2024-01, with the labels that each got.

#3 협업을 위한 기본 세팅
  screens/InitialPage.js
Labels: folder

#5 Added AsyncStorage to firebase.js
  firebase.js
Labels: feat

#7 testing css on login button
  screens/SignInPage.js
Labels: css

#9 crated css.js file
  screens/SignInPage.js
  screens/css.js
Labels: css

#10 Updated LogInPage
  App.js
  screens/InitialPage.js
  screens/LogInPage.js
  screens/TeamPage.js
Labels: feat, css

#14 Feat/#12
  App.js
  screens/UserInformationInputPage.js
Labels: feat

#17 Css/#15: InitialPage 가입하기 버튼 css 수정
  App.js
  screens/InitialPage.js
  screens/css.js
Labels: css

#18 Css/#15: InitialPage 가입하기 버튼 css 수정
  screens/InitialPage.js
  screens/css.js
Labels: css

#19 feat/#16: UserInformationInputPage 건너뛰기 버튼 추가
  App.js
  screens/InitialPage.js
  screens/SignInPage.js
  screens/UserInformationInputPage.js
Labels: feat

#21 Added Add Teammate Page
  App.js
  package-lock.json
  package.json
  screens/AddMembers.js
  screens/InitialPage.js
  screens/LogInPage.js
  screens/SignInPage.js
  screens/TeamPage.js
Labels: feat, css

#22 Add Teammate Page
  App.js
  package-lock.json
  package.json
  screens/AddMembers.js
  screens/InitialPage.js
  screens/LogInPage.js
  screens/SignInPage.js
  screens/TeamPage.js
Labels: feat, css

#26 Feat/#24 회원가입시 User ID FireStorage에 추가 + 유저정보 입력받기
  firebase.js
  package-lock.json
  package.json
  screens/SignInPage.js
  screens/UserInformationInputPage.js
Labels: feat

#33 feat/#30: 이메일 검증 기능 추가
  screens/components/SettingPage.js
  screens/logins/SignInPage.js
Labels: feat

#35 refactor/#34: SignInPage & UserInformationInputPage 병합
  App.js
  screens/InitialPage.js
  screens/components/SettingPage.js
  screens/logins/LogInPage.js
  screens/logins/SignInPage.js
  screens/logins/UserInformationInputPage.js
  screens/styles/css.js
Labels: refractor

#36 Comments/#32: 주석추가
  .gitignore
  .idea/.gitignore
  .idea/ToDoUniversity.iml
  .idea/modules.xml
  .idea/vcs.xml
  App.js
  app.json
  assets/adaptive-icon.png
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  babel.config.js
  package-lock.json
  package.json
  screens/components/Team/LogOutPage.js
  screens/components/Team/TeamPage.js
Labels: comments

#37 Comments/#32: 주석추가
  screens/components/Team/TeamPage.js
Labels: comments

#39 Feat/#38: 팀 add시 Firebase User's collection에 팀 ID 추가하기
  firebase.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamPage.js
Labels: feat

#42 Bug/#41: TeamPage에서 email 변수 저장 안되는 버그 수정
  screens/components/Team/TeamPage.js
Labels: bug

#43 Bug/#41 TeamPage에서 email 변수 저장 안되는 버그 수정 (재수정)
  screens/components/Team/TeamPage.js
Labels: bug

#46 Refractor/#45: 현재까지 작성된 코드 리펙터링
  App.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
Labels: refractor

#60 Feat/#53: 팀원 추가를 위한 이메일 발송
  App.js
  package-lock.json
  package.json
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamMemberAddPage_origin.js
  screens/components/Team/TeamUpdatePage.js
  screens/images/icons/glass_black.png
  screens/images/icons/glass_grey.png
  screens/images/icons/x.png
  screens/logins/AddMembers.js
Labels: feat

#65 Fix/#57: Team삭제시 firestorage, user, teamListCollection에서도 삭제가 진행되어야 함
  screens/components/AssignmentPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamMemberAddPage_origin.js
  screens/components/Team/TeamPage.js
  screens/images/icons/glass_black.png
  screens/images/icons/glass_grey.png
  screens/images/icons/x.png
Labels: fix

#66 Refactor/#59: SignInPage 정보 입력 수정하기
  App.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
Labels: refractor

#68 Fix/#62: 팀 생성시 확인 버튼 빠르게 누르면 팀이 여러개 생성 됨
  screens/components/Team/TeamAddPage.js
  screens/logins/UserInfoInputPage.js
Labels: fix

#69 bug/#67: 로그인 버그 수정
  App.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
Labels: bug

#72 Css/#56: Bottom Tab Navigator 스타일 수정
  App.js
Labels: css

#78 Css/#73: TeamPage 스타일 수정
  screens/InitialPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
  screens/components/Team/LogOutPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamMemberAddPage_origin.js
  screens/components/Team/TeamUpdatePage.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
  screens/styles/colors.js
Labels: css

#83 Css/#81: TeamMemberAddPage css 수정
  screens/components/Team/TeamMemberAddPage.js
  screens/styles/css.js
Labels: css

#85 Feat/#84: TeamMemberAddPage 동적 반응 수정
  screens/components/Team/TeamMemberAddPage.js
Labels: feat

#86 feat/#70: 로딩화면 추가
  App.js
  app.json
Labels: feat

#88 Css/#79: 폰트 추가하기
  assets/fonts/LICENSE
  assets/fonts/SUIT-Bold.ttf
  assets/fonts/SUIT-ExtraBold.ttf
  assets/fonts/SUIT-ExtraLight.ttf
  assets/fonts/SUIT-Heavy.ttf
  assets/fonts/SUIT-Light.ttf
  assets/fonts/SUIT-Medium.ttf
  assets/fonts/SUIT-Regular.ttf
  assets/fonts/SUIT-SemiBold.ttf
  assets/fonts/SUIT-Thin.ttf
  react-native.config.js
  screens/components/PersonalPage.js
Labels: css

#90 fix/#87: 회원가입 인증 버그 수정
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
Labels: fix

#93 Css/#92: TeamPage 스타일 변경
  screens/components/PersonalPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamItemPage_origin.js
  screens/components/Team/TeamPage.js
  screens/styles/css.js
Labels: css

#96 Css/#91: 폰트 전체 적용하기
  App.js
  assets/fonts/LICENSE
  assets/fonts/SUIT-Bold.ttf
  assets/fonts/SUIT-ExtraBold.ttf
  assets/fonts/SUIT-ExtraLight.ttf
  assets/fonts/SUIT-Heavy.ttf
  assets/fonts/SUIT-Light.ttf
  assets/fonts/SUIT-Medium.ttf
  assets/fonts/SUIT-Regular.ttf
  assets/fonts/SUIT-SemiBold.ttf
  assets/fonts/SUIT-Thin.ttf
  react-native.config.js
  screens/InitialPage.js
  screens/components/PersonalPage.js
  screens/components/SettingPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/styles/css.js
Labels: css

#97 Css/#95: TeamItem 파일 아이콘 크기 조정 (기기별 비율)
  screens/components/Team/TeamItem.js
Labels: css

#104 fix/#101: SignUpPage 가입하기 버튼 연속으로 못 누르게 수정
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
Labels: fix

#105 Css/#103: 로그인, 가입하기 버튼 -> 확인 버튼 으로 교체
  screens/logins/.LogInPage.js.swp
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
Labels: css

#106 Css/#102: 과제 추가 페이지 css 수정
  screens/components/AssignmentAddPage.js
  screens/components/Team/TeamMemberAddPage.js
Labels: css

#108 Css/#98: TeamPage Style 업데이트
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
Labels: css

#110 Css/#107: TeamMemberAddPage css 수정
  screens/components/Team/TeamMemberAddPage.js
  screens/images/icons/glass_black.png
  screens/styles/css.js
Labels: css

#112 Css/#109: TeamPage 파일 아이콘 간격 조정
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
Labels: css

#114 Css/#113: AssignmentPage Style 수정
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentPage.js
Labels: css

#117 Css/#116 : TeamPage Style Update
  package-lock.json
  package.json
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/images/icons/teamAdd_plus.png
  screens/images/icons/teamJoin.png
  screens/styles/colors.js
Labels: css

#120 Feat/#111: Toast 기능 구현
  App.js
  screens/components/PersonalPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamPage.js
  screens/components/Toast.js
  screens/images/icons/check.png
  screens/images/icons/glass_navy.png
Labels: feat

#130 feat/#119: Clipboard 기능 추가
  package-lock.json
  package.json
  screens/components/Team/TeamItem.js
Labels: feat

#127 Fix/#122: TeamMemberAddPage 보내기 버튼 비활성화
  screens/components/Team/TeamMemberAddPage.js
Labels: fix

#133 fix/#131: 가입 화면 이름/별명 필수로 바꾸기
  screens/logins/UserInfoInputPage.js
  screens/styles/css.js
Labels: fix

#136 feat/#135: PersonalPage에서 모달 창 추가 하기
  screens/components/PersonalPage.js
Labels: feat

#138 fix/#137: PersonalPage에서 모달 창 추가 하기
  screens/components/PersonalPage.js
Labels: fix

#139 feat/#118: AssignmentAddPage dueDate DatePicker로 변경
  package-lock.json
  package.json
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentPage.js
  screens/components/Team/TeamPage.js
Labels: css

#142 Css/#140: AssignmentPage Font Update
  screens/components/AssignmentItem.js
Labels: css

#145 bug/#144: PersonalPage 모달창 버그 수정
  screens/components/PersonalPage.js
Labels: bug

#146 Refractor/#143: 모든 모달창 수정
  screens/components/AssignmentItem.js
  screens/components/PersonalPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamMemberAddPage.js
  screens/components/Team/TeamPage.js
  screens/components/Team/TeamUpdatePage.js
Labels: refractor

#149 Fix/#147: 모달창 깜빡이는 버그 수정
  screens/components/AssignmentItem.js
  screens/components/PersonalPage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
  screens/components/Team/TeamUpdatePage.js
Labels: fix

#150 Css/#129: 팀 참여 페이지 확인 버튼 비활성화
  screens/components/AssignmentAddPage.js
  screens/components/Team/TeamJoinPage.js
  screens/styles/css.js
Labels: css

#156 Bug/#155: deleteItem -> leavingtheTeam으로 수정
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
Labels: bug

#157 Fix/#125: TeamPage 렌더링시 로딩화면 구현
  screens/components/Team/TeamPage.js
Labels: fix

#158 Feat/#128: TeamItem 모달창에 회원 정보 추가하기
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamPage.js
Labels: feat

#159 Feat/#153: AssignmentUpdatePage 수정
  screens/components/AssignmentUpdatePage.js
Labels: feat

#164 Fix/#162: 팀원추가 페이지 들어갈 때 팀 코드 전송
  screens/components/Team/TeamUpdateAddMemberPage.js
Labels: fix

#170 Css/#163: Toast Message 문제 해결
  screens/components/GuidancePage.js
  screens/components/Team/TeamJoinPage.js
  screens/components/Team/TeamPage.js
  screens/components/Toast.js
Labels: css

#172 Css/#165: 모달창 스타일 변경
  screens/components/AssignmentItem.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItem.js
  screens/components/Team/TeamUpdatePage.js
  screens/styles/css.js
Labels: css

#173 Feat/#167: 과제 화면에서 팀원 추가할 때 토스트 안 나오게 하기
  screens/components/AssignmentPage.js
Labels: feat

#175 Css/#168: 입력창 스타일 통일
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentItem.js
  screens/components/AssignmentUpdatePage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamJoinPage.js
  screens/styles/css.js
Labels: css

#178 Css/#115: TeamItem File Icon, AssignmentPage OpenedFile Icon Text Style 업데이트
  screens/components/AssignmentPage.js
  screens/components/Team/TeamItem.js
Labels: css

#179 Css/#177: 가입화면 TextInput 스타일 수정
  screens/components/AssignmentAddPage.js
  screens/components/AssignmentUpdatePage.js
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamUpdatePage.js
  screens/logins/LogInPage.js
  screens/logins/SignUpPage.js
  screens/logins/UserInfoInputPage.js
  screens/styles/css.js
Labels: css

#181 Feat/#176: 팀 필드에 member_id_array (문자열 배열) -> 객체 collection 로 변환 TeamAddPage에서 팀 추가시 멤버 객체 subcollection에 id:email로 추가 TeamJoinPage에서 팀 참여 멤버 객체 subcollection에 id:email로 추가 TeamPage leaveTeam함수 수정
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamItemPage_origin.js
  screens/components/Team/TeamJoinPage.js
  screens/components/Team/TeamMemberAddPage_origin.js
  screens/components/Team/TeamPage.js
  screens/logins/UserInfoInputPage.js
Labels: feat, refractor

#183 Css/#180: 색상 팔레트 확인버튼 비율 수정
  screens/components/Team/TeamAddPage.js
  screens/components/Team/TeamUpdatePage.js
Labels: css

#187 Css/#186: 모달창 버튼 위치 수정
  screens/components/AssignmentPage.js
  screens/components/Team/TeamItem.js
  screens/styles/css.js
Labels: css

#188 css/#148: 개인 화면 요소 넣기
  package-lock.json
  package.json
  screens/components/PersonalPage.js
  screens/components/PersonalPageFolder/PersonalPageBtn.js
  screens/components/PersonalPageFolder/WeeklyCalendar.js
  screens/components/PersonalPageFolder/src/Locale.js
  screens/components/PersonalPageFolder/src/Style.js
  screens/images/categoryAddBtn.png
  screens/images/categoryCloseBtn.png
  screens/images/icons/EditIcon.png
  screens/images/option.png
Labels: css

#191 fix/#189: PersonalPage 오류 수정
  screens/components/PersonalPage.js
Labels: fix
